name: SSH Command
inputs:
  action:
    required: true
    description: 'Command list: scp, ssh-command'
  host:
    required: true
  port:
    required: false
  user:
    required: true
  key:
    required: true
  script:
    required: false
  source:
    required: false
  target:
    required: false
  runs:
    using: 'docker'
    image: 'Dockerfile'